// ignore_for_file: file_names

import 'package:rjs_store/core/utils/constants/image_strings.dart';

class ProductsList {
  // Make the constructor private to prevent instantiation
  ProductsList._();

  /// A static list of product maps. Each map includes:
  /// - imageUrl: The path to the product asset.
  /// - productTitle: The name of the product.
  /// - brand: The brand name.
  /// - priceRange: A string indicating the price range for the product.

  static const List<Map<String, String>> products = [
    {
      'imageUrl': TImages.productImage1,
      'productTitle': 'Green Nike Sports Shoe',
      'brand': 'Nike',
      'priceRange': '\$122.6 - \$334.0',
    },
    {
      'imageUrl': TImages.productImage2,
      'productTitle': 'Blue Adidas Sports Shoe',
      'brand': 'Adidas',
      'priceRange': '\$150.0 - \$320.0',
    },
    {
      'imageUrl': TImages.productImage3,
      'productTitle': 'Urban Explorer Jacket',
      'brand': 'The North Face',
      'priceRange': '\$200.0 - \$450.0',
    },
    {
      'imageUrl': TImages.productImage4,
      'productTitle': 'Casual Denim Jeans',
      'brand': 'Levi\'s',
      'priceRange': '\$80.0 - \$120.0',
    },
    {
      'imageUrl': TImages.productImage5,
      'productTitle': 'Classic Casual Shirt',
      'brand': 'H&M',
      'priceRange': '\$40.0 - \$70.0',
    },
    {
      'imageUrl': TImages.productImage6,
      'productTitle': 'Sporty Slippers',
      'brand': 'Puma',
      'priceRange': '\$30.0 - \$50.0',
    },
    {
      'imageUrl': TImages.productImage7,
      'productTitle': 'Modern Air Sneakers',
      'brand': 'Nike',
      'priceRange': '\$110.0 - \$260.0',
    },
    {
      'imageUrl': TImages.productImage8,
      'productTitle': 'Vibrant Air Sneakers',
      'brand': 'Nike',
      'priceRange': '\$105.0 - \$250.0',
    },
    {
      'imageUrl': TImages.productImage9,
      'productTitle': 'Retro Air Classic',
      'brand': 'Nike',
      'priceRange': '\$100.0 - \$250.0',
    },
    {
      'imageUrl': TImages.productImage10,
      'productTitle': 'Nike Elite Court',
      'brand': 'Nike',
      'priceRange': '\$130.0 - \$300.0',
    },
    {
      'imageUrl': TImages.productImage11,
      'productTitle': 'Samsung Galaxy S9',
      'brand': 'Samsung',
      'priceRange': '\$300.0 - \$500.0',
    },
    {
      'imageUrl': TImages.productImage12,
      'productTitle': 'Galaxy S9 Rear View',
      'brand': 'Samsung',
      'priceRange': '\$300.0 - \$500.0',
    },
    {
      'imageUrl': TImages.productImage13,
      'productTitle': 'Galaxy S9 Backside',
      'brand': 'Samsung',
      'priceRange': '\$300.0 - \$500.0',
    },
    {
      'imageUrl': TImages.productImage14,
      'productTitle': 'iPhone 8 Front',
      'brand': 'Apple',
      'priceRange': '\$400.0 - \$600.0',
    },
    {
      'imageUrl': TImages.productImage15,
      'productTitle': 'iPhone 8 Rear',
      'brand': 'Apple',
      'priceRange': '\$400.0 - \$600.0',
    },
    {
      'imageUrl': TImages.productImage16,
      'productTitle': 'iPhone 8 Dual View',
      'brand': 'Apple',
      'priceRange': '\$400.0 - \$600.0',
    },
    {
      'imageUrl': TImages.productImage17,
      'productTitle': 'iPhone 8 Classic',
      'brand': 'Apple',
      'priceRange': '\$400.0 - \$600.0',
    },
    {
      'imageUrl': TImages.productImage18,
      'productTitle': 'Premium Dog Food',
      'brand': 'Tomi',
      'priceRange': '\$20.0 - \$35.0',
    },
    {
      'imageUrl': TImages.productImage19,
      'productTitle': 'Single Blue Sneaker',
      'brand': 'Nike',
      'priceRange': '\$110.0 - \$260.0',
    },
    {
      'imageUrl': TImages.productImage20,
      'productTitle': 'Single Orange Sneaker',
      'brand': 'Nike',
      'priceRange': '\$110.0 - \$260.0',
    },
    {
      'imageUrl': TImages.productImage21,
      'productTitle': 'Nike Air Max',
      'brand': 'Nike',
      'priceRange': '\$120.0 - \$280.0',
    },
    {
      'imageUrl': TImages.productImage22,
      'productTitle': 'Basketball Pro',
      'brand': 'Nike',
      'priceRange': '\$130.0 - \$300.0',
    },
    {
      'imageUrl': TImages.productImage23,
      'productTitle': 'Wildhorse Trail Shoe',
      'brand': 'Nike',
      'priceRange': '\$115.0 - \$270.0',
    },
    {
      'imageUrl': TImages.productImage24,
      'productTitle': 'Black Tracksuit',
      'brand': 'Adidas',
      'priceRange': '\$70.0 - \$150.0',
    },
    {
      'imageUrl': TImages.productImage25,
      'productTitle': 'Blue Tracksuit',
      'brand': 'Adidas',
      'priceRange': '\$70.0 - \$150.0',
    },
    {
      'imageUrl': TImages.productImage26,
      'productTitle': 'Red Tracksuit',
      'brand': 'Adidas',
      'priceRange': '\$70.0 - \$150.0',
    },
    {
      'imageUrl': TImages.productImage27,
      'productTitle': 'Parrot Green Tracksuit',
      'brand': 'Adidas',
      'priceRange': '\$70.0 - \$150.0',
    },
    {
      'imageUrl': TImages.productImage28,
      'productTitle': 'Adidas Football',
      'brand': 'Adidas',
      'priceRange': '\$25.0 - \$60.0',
    },
    {
      'imageUrl': TImages.productImage29,
      'productTitle': 'Baseball Bat',
      'brand': 'Rawlings',
      'priceRange': '\$50.0 - \$100.0',
    },
    {
      'imageUrl': TImages.productImage30,
      'productTitle': 'Cricket Bat',
      'brand': 'Kookaburra',
      'priceRange': '\$60.0 - \$120.0',
    },
    {
      'imageUrl': TImages.productImage31,
      'productTitle': 'Tennis Racket',
      'brand': 'Wilson',
      'priceRange': '\$80.0 - \$200.0',
    },
    {
      'imageUrl': TImages.productImage32,
      'productTitle': 'Modern Bedroom Bed',
      'brand': 'IKEA',
      'priceRange': '\$250.0 - \$600.0',
    },
    {
      'imageUrl': TImages.productImage33,
      'productTitle': 'Stylish Lamp',
      'brand': 'IKEA',
      'priceRange': '\$30.0 - \$80.0',
    },
    {
      'imageUrl': TImages.productImage34,
      'productTitle': 'Comfortable Sofa',
      'brand': 'IKEA',
      'priceRange': '\$300.0 - \$800.0',
    },
    {
      'imageUrl': TImages.productImage35,
      'productTitle': 'Spacious Wardrobe',
      'brand': 'IKEA',
      'priceRange': '\$150.0 - \$400.0',
    },
    // {
    //   'imageUrl': TImages.productImage36,
    //   'productTitle': 'Modern Kitchen Counter',
    //   'brand': 'IKEA',
    //   'priceRange': '\$200.0 - \$500.0',
    // },
    // {
    //   'imageUrl': TImages.productImage37,
    //   'productTitle': 'Dining Table',
    //   'brand': 'IKEA',
    //   'priceRange': '\$150.0 - \$450.0',
    // },
    // {
    //   'imageUrl': TImages.productImage38,
    //   'productTitle': 'Energy Efficient Refrigerator',
    //   'brand': 'LG',
    //   'priceRange': '\$400.0 - \$900.0',
    // },
    // {
    //   'imageUrl': TImages.productImage39,
    //   'productTitle': 'Ergonomic Office Chair',
    //   'brand': 'Herman Miller',
    //   'priceRange': '\$250.0 - \$700.0',
    // },
    // {
    //   'imageUrl': TImages.productImage40,
    //   'productTitle': 'Comfortable Office Chair',
    //   'brand': 'Herman Miller',
    //   'priceRange': '\$250.0 - \$700.0',
    // },
    // {
    //   'imageUrl': TImages.productImage41,
    //   'productTitle': 'Modern Office Desk',
    //   'brand': 'IKEA',
    //   'priceRange': '\$150.0 - \$350.0',
    // },
    // {
    //   'imageUrl': TImages.productImage42,
    //   'productTitle': 'Compact Office Desk',
    //   'brand': 'IKEA',
    //   'priceRange': '\$150.0 - \$350.0',
    // },
    // {
    //   'imageUrl': TImages.productImage43,
    //   'productTitle': 'Black Bedroom Bed',
    //   'brand': 'IKEA',
    //   'priceRange': '\$250.0 - \$600.0',
    // },
    // {
    //   'imageUrl': TImages.productImage44,
    //   'productTitle': 'Grey Bedroom Bed',
    //   'brand': 'IKEA',
    //   'priceRange': '\$250.0 - \$600.0',
    // },
    // {
    //   'imageUrl': TImages.productImage45,
    //   'productTitle': 'Simple Brown Bed',
    //   'brand': 'IKEA',
    //   'priceRange': '\$200.0 - \$500.0',
    // },
    // {
    //   'imageUrl': TImages.productImage46,
    //   'productTitle': 'Bed with Comforter',
    //   'brand': 'IKEA',
    //   'priceRange': '\$220.0 - \$520.0',
    // },
    // {
    //   'imageUrl': TImages.productImage47,
    //   'productTitle': 'Acer Laptop Model 1',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage48,
    //   'productTitle': 'Acer Laptop Model 2',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage49,
    //   'productTitle': 'Acer Laptop Model 3',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage50,
    //   'productTitle': 'Acer Laptop Model 4',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage51,
    //   'productTitle': 'iPhone 13 Pro',
    //   'brand': 'Apple',
    //   'priceRange': '\$900.0 - \$1500.0',
    // },
    // {
    //   'imageUrl': TImages.productImage52,
    //   'productTitle': 'iPhone 14 Pro',
    //   'brand': 'Apple',
    //   'priceRange': '\$1000.0 - \$1600.0',
    // },
    // {
    //   'imageUrl': TImages.productImage53,
    //   'productTitle': 'iPhone 14 (White)',
    //   'brand': 'Apple',
    //   'priceRange': '\$1000.0 - \$1600.0',
    // },
    // {
    //   'imageUrl': TImages.productImage54,
    //   'productTitle': 'Blue Casual Shirt',
    //   'brand': 'H&M',
    //   'priceRange': '\$30.0 - \$70.0',
    // },
    // {
    //   'imageUrl': TImages.productImage55,
    //   'productTitle': 'Blue Formal Shirt',
    //   'brand': 'H&M',
    //   'priceRange': '\$30.0 - \$70.0',
    // },
    // {
    //   'imageUrl': TImages.productImage56,
    //   'productTitle': 'Acer Vari Model 1',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage57,
    //   'productTitle': 'Acer Vari Model 2',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage58,
    //   'productTitle': 'Acer Vari Model 3',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage59,
    //   'productTitle': 'Acer Vari Model 4',
    //   'brand': 'Acer',
    //   'priceRange': '\$500.0 - \$800.0',
    // },
    // {
    //   'imageUrl': TImages.productImage60,
    //   'productTitle': 'Red Collar T-shirt',
    //   'brand': 'Zara',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage61,
    //   'productTitle': 'Yellow Collar T-shirt',
    //   'brand': 'Zara',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage62,
    //   'productTitle': 'Green Collar T-shirt',
    //   'brand': 'Zara',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage63,
    //   'productTitle': 'Blue Collar T-shirt',
    //   'brand': 'Zara',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage64,
    //   'productTitle': 'Leather Jacket Style 1',
    //   'brand': 'Guess',
    //   'priceRange': '\$120.0 - \$300.0',
    // },
    // {
    //   'imageUrl': TImages.productImage65,
    //   'productTitle': 'Leather Jacket Style 2',
    //   'brand': 'Guess',
    //   'priceRange': '\$120.0 - \$300.0',
    // },
    // {
    //   'imageUrl': TImages.productImage66,
    //   'productTitle': 'Leather Jacket Style 3',
    //   'brand': 'Guess',
    //   'priceRange': '\$120.0 - \$300.0',
    // },
    // {
    //   'imageUrl': TImages.productImage67,
    //   'productTitle': 'Leather Jacket Style 4',
    //   'brand': 'Guess',
    //   'priceRange': '\$120.0 - \$300.0',
    // },
    // {
    //   'imageUrl': TImages.productImage68,
    //   'productTitle': 'Blue T-shirt (Back)',
    //   'brand': 'Uniqlo',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage69,
    //   'productTitle': 'Blue T-shirt (Front)',
    //   'brand': 'Uniqlo',
    //   'priceRange': '\$20.0 - \$40.0',
    // },
    // {
    //   'imageUrl': TImages.productImage70,
    //   'productTitle': 'iPhone 12 (Red)',
    //   'brand': 'Apple',
    //   'priceRange': '\$800.0 - \$1200.0',
    // },
    // {
    //   'imageUrl': TImages.productImage71,
    //   'productTitle': 'iPhone 12 (Blue)',
    //   'brand': 'Apple',
    //   'priceRange': '\$800.0 - \$1200.0',
    // },
    // {
    //   'imageUrl': TImages.productImage72,
    //   'productTitle': 'iPhone 12 (Green)',
    //   'brand': 'Apple',
    //   'priceRange': '\$800.0 - \$1200.0',
    // },
    // {
    //   'imageUrl': TImages.productImage73,
    //   'productTitle': 'iPhone 12 (Black)',
    //   'brand': 'Apple',
    //   'priceRange': '\$800.0 - \$1200.0',
    // },
    // {
    //   'imageUrl': TImages.productImage74,
    //   'productTitle': 'Casual Slipper 1',
    //   'brand': 'Clarks',
    //   'priceRange': '\$30.0 - \$60.0',
    // },
    // {
    //   'imageUrl': TImages.productImage75,
    //   'productTitle': 'Casual Slipper 2',
    //   'brand': 'Clarks',
    //   'priceRange': '\$30.0 - \$60.0',
    // },
    // {
    //   'imageUrl': TImages.productImage76,
    //   'productTitle': 'Casual Slipper 3',
    //   'brand': 'Clarks',
    //   'priceRange': '\$30.0 - \$60.0',
    // },
    // {
    //   'imageUrl': TImages.productImage77,
    //   'productTitle': 'Ultimate Casual Slipper',
    //   'brand': 'Clarks',
    //   'priceRange': '\$30.0 - \$60.0',
    // },
    // You can continue adding more products
  ];
}
